#!/bin/bash

COMMAND=$1

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

if [ -z "$COMMAND" ]; then
    echo
    echo "GRC: No command passed."
    echo
    exit 0
fi

python3 $SCRIPT_DIR/.program-files/main.py $@
