#!/bin/bash

COMMAND=$1

if [ -z "$COMMAND" ]; then
    echo
    echo "GRC: No command specified."
    echo
    exit 1
fi

source /opt/grc/GitHub-Repo-Creator/venv/bin/activate
python /opt/grc/GitHub-Repo-Creator/.program-files/main.py $@
EXIT_CODE=$?
deactivate

exit $EXIT_CODE
