#!/bin/bash

COMMAND=$1
PARAMETER=$2

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

if [ -z "$COMMAND" ]; then
    echo
    echo "GRC: No command passed."
    echo
    exit 0
fi

if [ -z "$PARAMETER" ]; then
    python3 $SCRIPT_DIR/.program-files/main.py $COMMAND
else
    if [ $COMMAND = "create" ] || [ $COMMAND = "save" ]; then
        if [[ "$PARAMETER" = /* ]]; then
            python3 $SCRIPT_DIR/.program-files/main.py $COMMAND $PARAMETER
        else
            FILE_PATH=$PWD/$PARAMETER
            python3 $SCRIPT_DIR/.program-files/main.py $COMMAND $FILE_PATH
        fi     
    else
        python3 $SCRIPT_DIR/.program-files/main.py $COMMAND $PARAMETER
    fi
fi
