@ECHO OFF

SET COMMAND=%1
SET PARAMETER=%2

:COMMAND
IF DEFINED COMMAND GOTO PARAMETER

ECHO.
ECHO No command passed.
ECHO.
EXIT

:PARAMETER
IF DEFINED PARAMETER GOTO PARAMETER_COMMANDS
GOTO NO_PARAMETER_COMMANDS

:PARAMETER_COMMANDS
IF %COMMAND%==create GOTO CREATE
IF %COMMAND%==save GOTO SAVE
IF %COMMAND%==authenticate GOTO AUTHENTICATE

:CREATE
SET FILE_PATH=%CD%\%PARAMETER%
python %~dp0.program-files/main.py %COMMAND% %FILE_PATH%
EXIT

:SAVE
SET FILE_PATH=%CD%\%PARAMETER%
python %~dp0.program-files/main.py %COMMAND% %FILE_PATH%
EXIT

:AUTHENTICATE
python %~dp0.program-files/main.py %COMMAND% %PARAMETER%
EXIT

:NO_PARAMETER_COMMANDS
EXIT