name: Format Code
on: pull_request
jobs:
  autopep8:
    # Check if the PR is not from a fork.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Autopep8
        id: autopep8
        uses: peter-evans/autopep8@v1
        with:
          args: --exit-code --recursive --in-place --aggressive --aggressive .program-files
      - name: Commit Autopep8 Changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'action@github.com'
          git commit -am "(Auto) Code Formatting."
          git push